// lib/services/app_settings.dart
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage { id, en }

class AppSettings extends ChangeNotifier {
  AppSettings._();
  static final AppSettings instance = AppSettings._();

  double textScale = 1.0;
  bool highContrast = false;
  AppLanguage language = AppLanguage.id;

  static const _kTextScale = 'settings_text_scale';
  static const _kHighContrast = 'settings_high_contrast';
  static const _kLanguage = 'settings_language';

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    textScale = prefs.getDouble(_kTextScale) ?? 1.0;
    highContrast = prefs.getBool(_kHighContrast) ?? false;
    final langStr = prefs.getString(_kLanguage);
    language = langStr == 'en' ? AppLanguage.en : AppLanguage.id;
    notifyListeners();
  }

  Future<void> setTextScale(double scale) async {
    textScale = scale;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setDouble(_kTextScale, scale);
    notifyListeners();
  }

  Future<void> setHighContrast(bool value) async {
    highContrast = value;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_kHighContrast, value);
    notifyListeners();
  }

  Future<void> setLanguage(AppLanguage lang) async {
    language = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_kLanguage, lang == AppLanguage.en ? 'en' : 'id');
    notifyListeners();
  }
}

class AppStrings {
  static String t(String key) {
    final lang = AppSettings.instance.language;
    final map = lang == AppLanguage.en ? _en : _id;
    return map[key] ?? key;
  }

  static const _id = {
    // Bottom nav
    'nav_search': 'Search',
    'nav_bookings': 'Bookings',
    'nav_alerts': 'Alerts',
    'nav_profile': 'Profile',

    'loc_facilities_title': 'Fasilitas Keamanan',
    'loc_accessible_note':
        'Lokasi ini ramah untuk lansia & pengguna kursi roda (dekat lift/gate).',
    'loc_location_title': 'Lokasi',
    'loc_per_night': ' / malam',
    'loc_km_from_airport': 'km dari bandara',
    'loc_select_slot_btn': 'Pilih Slot Ini',
    'loc_reviews_title': 'Ulasan Pengguna',
    'loc_reviews_suffix': 'ulasan',
    'loc_no_reviews': 'Belum ada ulasan untuk lokasi ini.',

    // Search screen
    'search_appbar_title': 'ParkirIn',
    'search_hero_badge': 'PARK & FLY',
    'search_title_1': 'Solusi Parkir Inap\nBandara yang ',
    'search_title_2': 'Aman & Mudah',
    'search_pilih_bandara': 'PILIH BANDARA',
    'search_masuk': 'MASUK',
    'search_keluar': 'KELUAR',
    'search_cta': 'Cari Slot Parkir',
    'search_promo_badge': 'PROMO PENGGUNA BARU',
    'search_promo_title': 'Diskon 20%',
    'search_promo_code_label': 'Gunakan kode: ',
    'search_ground_transport_title': 'Transportasi Lanjutan',
    'search_ground_transport_sub':
        'Taksi, bus, travel, kereta bandara, dan lainnya.',
    'search_why_title': 'Kenapa Pilih ParkirIn?',
    'search_feature_slot_title': 'Slot Terjamin',
    'search_feature_slot_sub': 'Pasti dapat tempat, fasilitas aman 24/7.',
    'search_feature_biaya_title': 'Biaya Transparan',
    'search_feature_biaya_sub': 'Tanpa biaya tersembunyi saat checkout.',
    'search_shuttle_title': 'Lacak Shuttle Real-time',
    'search_shuttle_sub':
        'Pantau posisi bus jemputan langsung dari HP anda menuju terminal.',
    'search_active_booking_parked': 'Kendaraan Sedang Parkir',
    'search_active_booking_waiting': 'Booking Aktif Menunggu Check-in',
    'search_malam': 'malam',

    // Bookings screen
    'bookings_appbar_title': 'My Bookings',
    'bookings_tab_aktif': 'Aktif',
    'bookings_tab_selesai': 'Selesai',
    'bookings_tab_dibatalkan': 'Dibatalkan',
    'bookings_tab_kedaluwarsa': 'Kedaluwarsa',
    'bookings_empty': 'Belum ada booking',
    'bookings_slot_label': 'Slot',
    'bookings_checkin_btn': 'Check-in',
    'bookings_checkout_btn': 'Check-out',
    'bookings_qr_btn': 'Lihat QR Code',
    'bookings_expired_note':
        'Dibatalkan otomatis karena tidak check-in sesuai batas waktu',

    // Profile screen
    'profile_appbar_title': 'Profile',
    'profile_gold_member': 'Gold Member',
    'profile_my_details_title': 'My Details',
    'profile_my_details_sub': 'Personal info, ID, password',
    'profile_payment_title': 'Payment Methods',
    'profile_payment_sub': 'Cards, e-wallets, bank transfer',
    'profile_help_title': 'Help Center',
    'profile_help_sub': 'FAQs, contact support',
    'profile_favorites_title': 'Favorit Saya',
    'profile_favorites_sub': 'Lokasi parkir yang Anda simpan',
    'profile_notif_settings_title': 'Pengaturan Notifikasi',
    'profile_notif_settings_sub': 'Atur jenis notifikasi yang diterima',
    'profile_vehicles_title': 'Kendaraan Saya',
    'profile_vehicles_sub': 'Kelola plat nomor tersimpan',
    'profile_invoice_title': 'Riwayat Invoice',
    'profile_invoice_sub': 'Unduh struk transaksi Anda',
    'profile_loyalty_title': 'Loyalty & Membership',
    'profile_referral_title': 'Undang Teman',
    'profile_referral_sub': 'Dapatkan Rp 25.000 per referral',
    'profile_terms_title': 'Syarat & Ketentuan',
    'profile_terms_sub': 'Kebijakan layanan & privasi',
    'profile_accessibility_title': 'Aksesibilitas',
    'profile_accessibility_sub': 'Ukuran teks & kontras tinggi',
    'profile_language_title': 'Bahasa',
    'profile_language_sub': 'Indonesia / English',
    'profile_delete_account_title': 'Hapus Akun & Data',
    'profile_delete_account_sub': 'Kelola atau hapus data pribadi Anda',
    'profile_logout': 'Logout',
    'profile_logout_confirm_title': 'Logout',
    'profile_logout_confirm_msg': 'Apakah anda yakin ingin keluar?',
    'profile_cancel': 'Batal',

    // Notifications screen
    'notif_title': 'Notifications',
    'notif_subtitle': 'Stay updated on your upcoming trips and shuttle status.',
    'notif_mark_all_read': 'Tandai semua dibaca',
    'notif_pilih': 'Pilih',
    'notif_batal': 'Batal',
    'notif_filter_semua': 'Semua',
    'notif_filter_reminder': 'Reminder',
    'notif_filter_shuttle': 'Shuttle',
    'notif_filter_booking': 'Booking',
    'notif_filter_flight': 'Penerbangan',
    'notif_group_today': 'Hari Ini',
    'notif_group_yesterday': 'Kemarin',
    'notif_group_week': 'Minggu Ini',
    'notif_group_older': 'Lebih Lama',
    'notif_empty_title': 'Belum ada notifikasi',
    'notif_empty_sub':
        'Update booking, shuttle, dan penerbangan Anda\nakan muncul di sini.',
    'notif_mark_read_btn': 'Tandai Dibaca',
    'notif_delete_btn': 'Hapus',
    'notif_appbar_title': 'Alerts',
    'notif_new_badge_suffix': 'baru',
    'notif_booking_code_label': 'Kode booking: ',
    'notif_phase2_badge': 'Fase 2',
    'slot_map_title': 'Pilih Slot Parkir',
    'slot_legend_premium': 'Premium (dekat pintu masuk)',
    'slot_legend_standard': 'Standar',
    'slot_legend_economy': 'Ekonomis (jauh)',
    'slot_legend_occupied': 'Terisi',
    'slot_akses_jalan': 'Akses Jalan',
    'slot_select_first': 'Pilih Slot Terlebih Dahulu',
    'slot_continue_with': 'Lanjutkan dengan Slot',
    'slot_baris_label': 'Baris',
    'slot_dari_pintu_masuk': 'm dari pintu masuk',
    'slot_per_malam': '/malam',
    'vehicle_appbar_title': 'Pilih Kendaraan',
    'vehicle_slot_prefix': 'Slot',
    'vehicle_per_malam': '/malam',
    'vehicle_pilih_title': 'Pilih Kendaraan',
    'vehicle_tambah_btn': 'Tambah',
    'vehicle_utama_badge': 'UTAMA',
    'vehicle_lanjut_btn': 'Lanjutkan ke Ringkasan',
    'vehicle_empty_title': 'Belum ada kendaraan tersimpan',
    'vehicle_empty_btn': 'Tambah Kendaraan',
    'vehicle_lock_expired_title': 'Waktu Habis',
    'vehicle_lock_expired_msg':
        'Slot yang Anda pilih telah dilepas karena waktu penguncian habis. Silakan pilih slot kembali.',
    'vehicle_back_home_btn': 'Kembali ke Beranda',
    'summary_appbar_title': 'Ringkasan & Pembayaran',
    'summary_masuk': 'MASUK',
    'summary_keluar': 'KELUAR',
    'summary_malam': 'malam',
    'summary_slot_prefix': 'Slot',
    'summary_rincian_biaya': 'Rincian Biaya',
    'summary_tarif_dasar': 'Tarif dasar',
    'summary_biaya_layanan': 'Biaya layanan',
    'summary_total': 'Total',
    'summary_total_label': 'Total  ',
    'summary_metode_pembayaran': 'Metode Pembayaran',
    'summary_opsional_badge': 'Opsional',
    'summary_bayar_sekarang': 'Bayar Sekarang',
    'summary_overstay_notice':
        'Biaya tambahan (overstay fee) akan dikenakan otomatis jika Anda melebihi durasi yang dipesan. Anda akan mendapat notifikasi sebelum batas waktu habis.',
    'summary_notif_title': 'Booking Berhasil Dikonfirmasi',
    'summary_notif_desc_prefix': 'Slot',
    'summary_notif_desc_suffix': 'telah dikonfirmasi.',
    'summary_notif_action': 'Lihat QR Code',
    'confirm_title': 'Booking Berhasil!',
    'confirm_subtitle':
        'Konfirmasi & QR Code telah dikirim untuk booking Anda.',
    'confirm_qr_note': 'Tunjukkan QR Code ini saat check-in & check-out',
    'confirm_masuk': 'Masuk',
    'confirm_keluar': 'Keluar',
    'confirm_total_dibayar': 'Total Dibayar',
    'confirm_reminder_note':
        'Kami akan mengirim reminder 1 hari sebelum jadwal check-in Anda.',
    'confirm_lihat_booking_btn': 'Lihat Booking Saya',
    'confirm_kembali_beranda_btn': 'Kembali ke Beranda',
    'checkin_appbar_title': 'Check-in',
    'checkin_waiting_title': 'Tunjukkan QR ini di gerbang masuk',
    'checkin_success_title': 'Check-in Berhasil',
    'checkin_waiting_sub': 'Petugas atau kiosk akan memindai QR Code ini',
    'checkin_success_sub': 'Kendaraan Anda tercatat aman di area parkir',
    'checkin_waiting_qr_status': 'Menunggu validasi gerbang...',
    'checkin_success_banner': 'QR berhasil divalidasi oleh gerbang masuk',
    'checkin_photo_toggle': 'Opsional: Dokumentasikan Kondisi Kendaraan',
    'checkin_photo_note':
        'Untuk membantu klaim jika terjadi kerusakan selama parkir.',
    'checkin_photo_depan': 'Depan',
    'checkin_photo_belakang': 'Belakang',
    'checkin_photo_kiri': 'Kiri',
    'checkin_photo_kanan': 'Kanan',
    'checkin_lacak_shuttle_btn': 'Lacak Shuttle',
    'checkin_notif_title': 'Check-in Berhasil',
    'checkin_notif_desc_prefix': 'Kendaraan',
    'checkin_notif_desc_middle': 'tercatat aman di slot',
    'checkin_notif_action': 'Lihat Booking',
    'checkout_overstay_warning':
        'Anda melebihi durasi booking. Biaya tambahan {amount} akan otomatis ditambahkan sebelum portal keluar dapat digunakan.',
    'checkout_appbar_title': 'Check-out',
    'checkout_waiting_title': 'Tunjukkan QR ini di gerbang keluar',
    'checkout_waiting_sub': 'Petugas atau kiosk akan memindai QR Code ini',
    'checkout_waiting_qr_status': 'Menunggu validasi gerbang...',
    'checkout_photo_toggle': 'Opsional: Verifikasi Akhir Kondisi Kendaraan',
    'checkout_photo_depan': 'Depan',
    'checkout_photo_belakang': 'Belakang',
    'checkout_photo_kiri': 'Kiri',
    'checkout_photo_kanan': 'Kanan',
    'checkout_invoice_title': 'Invoice Final',
    'checkout_success_title': 'Check-out Berhasil',
    'checkout_success_sub': 'Lot parkir Anda telah kembali tersedia',
    'checkout_kode_booking': 'Kode Booking:',
    'checkout_tarif_dasar': 'Tarif dasar',
    'checkout_malam': 'malam',
    'checkout_biaya_layanan': 'Biaya layanan',
    'checkout_biaya_keterlambatan': 'Biaya keterlambatan',
    'checkout_total_akhir': 'Total Akhir',
    'checkout_selesai_btn': 'Selesai',
    'checkout_transport_btn': 'Cari Transportasi Lanjutan',
    'checkout_notif_success_title': 'Kendaraan Berhasil Diambil',
    'checkout_notif_success_desc':
        'Kendaraan {plate} berhasil check-out. Terima kasih!',
    'checkout_notif_success_action': 'Lihat Invoice',
    'checkout_notif_overstay_title': 'Biaya Keterlambatan Dikenakan',
    'checkout_notif_overstay_desc':
        'Booking {code} dikenakan biaya tambahan {amount}.',
    'checkout_notif_overstay_action': 'Lihat Detail',
    'shuttle_appbar_title': 'Lacak Shuttle',
    'shuttle_walking_title': 'Arah ke Halte Terdekat',
    'shuttle_slot_anda': 'Slot Anda',
    'shuttle_halte_terdekat': 'Halte Terdekat',
    'shuttle_meter_suffix': 'meter',
    'shuttle_menit_jalan_kaki': 'menit jalan kaki',
    'shuttle_petunjuk_arah_btn': 'Buka Petunjuk Arah',
    'shuttle_maps_error': 'Tidak dapat membuka aplikasi peta',
    'shuttle_rute_title': 'Rute Shuttle',
    'shuttle_titik_jemput': 'Titik Jemput',
    'shuttle_titik_terminal': 'Titik Terminal',
    'shuttle_berangkat_section': 'Shuttle Sedang Berangkat',
    'shuttle_standby_section': 'Shuttle Standby di Terminal',
    'shuttle_empty_berangkat':
        'Tidak ada shuttle yang sedang dalam perjalanan saat ini.',
    'shuttle_empty_standby': 'Tidak ada shuttle yang standby saat ini.',
    'shuttle_baru_lewat': 'Baru saja lewat:',
    'shuttle_menuju': 'Menuju:',
    'shuttle_standby_di': 'Standby di',
    'shuttle_siap_berangkat': 'Siap Berangkat',
    'shuttle_prefix': 'Shuttle',
    'shuttle_notif_title': 'Shuttle Tersedia di Halte Terdekat',
    'shuttle_notif_desc':
        'Shuttle sudah standby di {halte}, siap mengantar Anda.',
    'shuttle_notif_action': 'Lacak Shuttle',
    'mydetails_appbar_title': 'My Details',
    'mydetails_section_personal': 'Informasi Personal',
    'mydetails_nama': 'Nama Lengkap',
    'mydetails_email': 'Email',
    'mydetails_telepon': 'Nomor Telepon',
    'mydetails_section_identitas': 'Identitas (KTP/SIM)',
    'mydetails_nomor_identitas': 'Nomor Identitas',
    'mydetails_section_keamanan': 'Keamanan',
    'mydetails_ubah_password': 'Ubah Password',
    'mydetails_simpan_btn': 'Simpan Perubahan',
    'mydetails_saved_snackbar': 'Data berhasil disimpan',
    'mydetails_password_lama': 'Password Lama',
    'mydetails_password_baru': 'Password Baru',
    'mydetails_simpan_password_btn': 'Simpan Password Baru',

    'payment_appbar_title': 'Payment Methods',
    'payment_utama_badge': 'UTAMA',
    'payment_jadikan_utama': 'Jadikan Utama',
    'payment_hapus': 'Hapus',
    'payment_tambah_btn': 'Tambah Metode Pembayaran',
    'payment_kartu': 'Kartu Debit/Kredit',
    'payment_ewallet': 'E-Wallet (GoPay/OVO/Dana)',
    'payment_va': 'Virtual Account',

    'addpayment_title_card': 'Tambah Kartu Debit/Kredit',
    'addpayment_title_ewallet': 'Tambah E-Wallet',
    'addpayment_title_va': 'Tambah Virtual Account',
    'addpayment_nomor_kartu': 'Nomor Kartu',
    'addpayment_nama_pemegang': 'Nama Pemegang Kartu',
    'addpayment_nama_hint': 'Sesuai kartu',
    'addpayment_masa_berlaku': 'MM/YY',
    'addpayment_cvv': 'CVV',
    'addpayment_nomor_hp': 'Nomor HP Terdaftar',
    'addpayment_ewallet_note':
        'Anda akan diarahkan ke aplikasi e-wallet untuk verifikasi.',
    'addpayment_pilih_bank': 'Pilih Bank',
    'addpayment_va_note':
        'Nomor VA akan digenerate otomatis setelah konfirmasi.',
    'addpayment_security_note':
        'Data pembayaran Anda terenkripsi dan disimpan secara aman.',
    'addpayment_simpan_btn': 'Simpan',
    'addpayment_wajib_diisi': 'Wajib diisi',
    'addpayment_success_snackbar': 'Metode pembayaran berhasil ditambahkan',

    'fav_appbar_title': 'Favorit Saya',
    'fav_empty_title': 'Belum ada lokasi favorit',
    'fav_empty_sub': 'Tap ikon hati di hasil pencarian untuk menyimpan lokasi.',
    'fav_per_malam': '/malam',

    'vehicles_appbar_title': 'Kendaraan Saya',
    'vehicles_utama_badge': 'UTAMA',
    'vehicles_jadikan_utama': 'Jadikan Utama',
    'vehicles_hapus': 'Hapus',
    'vehicles_tambah_btn': 'Tambah Kendaraan',
    'vehicles_dialog_title': 'Tambah Kendaraan',
    'vehicles_plat_nomor': 'Plat Nomor',
    'vehicles_merek_model': 'Merek & Model',
    'vehicles_tipe': 'Tipe (SUV/MPV)',
    'vehicles_warna': 'Warna',
    'vehicles_simpan_btn': 'Simpan Kendaraan',

    'help_appbar_title': 'Help Center',
    'help_search_hint': 'Cari pertanyaan...',
    'help_faq_title': 'Pertanyaan yang Sering Diajukan',
    'help_no_results': 'Tidak ditemukan pertanyaan yang cocok',
    'help_more_help': 'Masih Butuh Bantuan?',
    'help_livechat_title': 'Live Chat 24 Jam',
    'help_livechat_sub': 'Terhubung dengan tim Customer Support kami',
    'help_report_title': 'Lapor Masalah / Komplain',
    'help_faq_q1': 'Bagaimana cara membatalkan booking?',
    'help_faq_a1':
        'Buka menu Bookings > pilih booking aktif > Reschedule/Batalkan. Pembatalan gratis jika dilakukan minimal 24 jam sebelum jadwal check-in.',
    'help_faq_q2': 'Apa yang terjadi jika saya terlambat check-out?',
    'help_faq_a2':
        'Sistem akan menghitung biaya tambahan (overstay fee) secara otomatis berdasarkan durasi keterlambatan. Anda akan menerima notifikasi peringatan sebelum batas waktu habis.',
    'help_faq_q3': 'Bagaimana jika kendaraan saya rusak selama dititipkan?',
    'help_faq_a3':
        'Kami mendokumentasikan foto kondisi kendaraan saat check-in dan check-out sebagai bukti klaim. Hubungi Customer Support untuk proses klaim lebih lanjut.',
    'help_faq_q4': 'Apakah saya bisa mengubah metode pembayaran?',
    'help_faq_a4':
        'Ya, kelola metode pembayaran Anda di menu Profile > Payment Methods.',
    'help_faq_q5': 'Bagaimana cara melacak shuttle?',
    'help_faq_a5':
        'Buka detail booking aktif Anda, lalu tekan tombol "Lacak Shuttle" untuk melihat posisi dan estimasi waktu kedatangan secara real-time.',

    'chat_appbar_online': 'Online 24 Jam',
    'chat_sos_btn': 'SOS',
    'chat_sos_dialog_title': 'Panggilan Darurat (SOS)',
    'chat_sos_dialog_msg':
        'Ini akan menghubungkan Anda langsung dengan petugas keamanan/hotline darurat di lokasi parkir. Lanjutkan?',
    'chat_sos_batal': 'Batal',
    'chat_sos_confirm': 'Ya, Hubungi Sekarang',
    'chat_sos_connecting': 'Menghubungkan ke petugas darurat...',
    'chat_input_hint': 'Tulis pesan...',
    'chat_greeting':
        'Halo Budi! Ada yang bisa kami bantu terkait booking parkir Anda?',
    'chat_autoresponse':
        'Terima kasih atas pesannya. Tim kami akan segera membantu Anda.',

    'report_appbar_title': 'Lapor Masalah',
    'report_booking_terkait': 'Terkait booking:',
    'report_kategori_title': 'Kategori Masalah',
    'report_deskripsi_title': 'Deskripsi Masalah',
    'report_deskripsi_hint':
        'Jelaskan masalah yang Anda alami secara detail...',
    'report_lampiran_title': 'Lampirkan Foto Bukti (opsional)',
    'report_kirim_btn': 'Kirim Laporan',
    'report_validation_snackbar': 'Lengkapi kategori dan deskripsi masalah',
    'report_success_title': 'Laporan Terkirim',
    'report_success_msg':
        'Tim kami akan meninjau laporan Anda dan menghubungi dalam 1x24 jam.',
    'report_selesai_btn': 'Selesai',
    'report_kategori_1': 'Kendaraan Rusak/Tergores',
    'report_kategori_2': 'Biaya Tidak Sesuai',
    'report_kategori_3': 'Shuttle Tidak Datang',
    'report_kategori_4': 'Petugas Tidak Ramah',
    'report_kategori_5': 'Masalah Pembayaran',
    'report_kategori_6': 'Lainnya',

    'accessibility_appbar_title': 'Aksesibilitas',
    'accessibility_ukuran_teks': 'Ukuran Teks',
    'accessibility_contoh_teks': 'Contoh teks pada ukuran ini',
    'accessibility_kontras_tinggi': 'Kontras Tinggi',
    'accessibility_kontras_sub':
        'Mempertajam warna utama agar lebih mudah dibaca',

    'language_appbar_title': 'Bahasa',
    'language_note':
        'Saat ini terjemahan mencakup navigasi utama dan sebagian besar halaman aplikasi.',

    'delete_appbar_title': 'Hapus Akun & Data',
    'delete_unduh_data_title': 'Unduh Data Saya',
    'delete_unduh_data_sub': 'Dapatkan salinan seluruh data pribadi Anda',
    'delete_minta_btn': 'Minta',
    'delete_warning':
        'Menghapus akun akan menghilangkan seluruh riwayat booking, poin loyalty, saldo wallet, dan data kendaraan Anda secara permanen.',
    'delete_reason_title': 'Mengapa Anda ingin menghapus akun?',
    'delete_feedback_hint': 'Masukan tambahan (opsional)',
    'delete_confirm_checkbox':
        'Saya memahami tindakan ini permanen dan tidak dapat dibatalkan',
    'delete_hapus_btn': 'Hapus Akun Saya',
    'delete_final_title': 'Konfirmasi Terakhir',
    'delete_final_msg':
        'Akun dan seluruh data pribadi Anda (riwayat booking, kendaraan, metode pembayaran) akan dihapus permanen dalam 30 hari. Tindakan ini tidak dapat dibatalkan setelah masa tenggang berakhir.',
    'delete_batal': 'Batal',
    'delete_ajukan_btn': 'Ajukan Penghapusan',
    'delete_submitted_title': 'Permintaan Diajukan',
    'delete_submitted_msg':
        'Kami telah menerima permintaan penghapusan akun Anda. Konfirmasi akan dikirim ke email terdaftar dalam 1x24 jam.',
    'delete_selesai_btn': 'Selesai',
    'delete_export_snackbar':
        'Permintaan ekspor data dikirim. Anda akan menerima email berisi salinan data dalam 1x24 jam.',
    'delete_reason_1': 'Tidak lagi membutuhkan layanan',
    'delete_reason_2': 'Menemukan alternatif lain',
    'delete_reason_3': 'Masalah privasi/keamanan',
    'delete_reason_4': 'Sulit digunakan',
    'delete_reason_5': 'Lainnya',
    'forgot_title': 'Lupa Password',
    'forgot_subtitle':
        'Masukkan email atau nomor HP yang terdaftar. Kami akan mengirimkan kode verifikasi untuk mengatur ulang password Anda.',
    'forgot_toggle_email': 'Email',
    'forgot_toggle_phone': 'Nomor HP',
    'forgot_email_label': 'Email',
    'forgot_phone_label': 'Nomor HP',
    'forgot_phone_hint': '08xxxxxxxxxx',
    'forgot_kirim_kode_btn': 'Kirim Kode Verifikasi',
    'forgot_kembali_login': 'Kembali ke Halaman Masuk',
    'forgot_not_found_error': 'Akun dengan kontak ini tidak ditemukan',

    'resetotp_title': 'Verifikasi Kode',
    'resetotp_subtitle_prefix': 'Kode verifikasi telah dikirim ke',
    'resetotp_verify_btn': 'Verifikasi',
    'resetotp_resend_prefix': 'Kirim ulang kode dalam',
    'resetotp_resend_btn': 'Kirim Ulang Kode',
    'resetotp_error': 'Masukkan 6 digit kode OTP',

    'newpass_title': 'Buat Password Baru',
    'newpass_subtitle':
        'Password baru harus berbeda dari password sebelumnya dan minimal 8 karakter.',
    'newpass_field1': 'Password Baru',
    'newpass_field2': 'Konfirmasi Password Baru',
    'newpass_simpan_btn': 'Simpan Password Baru',
    'newpass_error_short': 'Password minimal 8 karakter',
    'newpass_error_mismatch': 'Konfirmasi password tidak cocok',
    'newpass_success_title': 'Password Berhasil Diubah',
    'newpass_success_msg':
        'Silakan masuk kembali menggunakan password baru Anda.',
    'newpass_success_btn': 'Masuk Sekarang',
  };

  static const _en = {
    'nav_search': 'Search',
    'nav_bookings': 'Bookings',
    'nav_alerts': 'Alerts',
    'nav_profile': 'Profile',
    'search_appbar_title': 'ParkirIn',
    'search_hero_badge': 'PARK & FLY',
    'search_title_1': 'Airport Overnight\nParking Made ',
    'search_title_2': 'Safe & Easy',
    'search_pilih_bandara': 'SELECT AIRPORT',
    'search_masuk': 'CHECK-IN',
    'search_keluar': 'CHECK-OUT',
    'search_cta': 'Find Parking Slot',
    'search_promo_badge': 'NEW USER PROMO',
    'search_promo_title': '20% Off',
    'search_promo_code_label': 'Use code: ',
    'search_ground_transport_title': 'Onward Transport',
    'search_ground_transport_sub':
        'Taxi, bus, shuttle, airport train, and more.',
    'search_why_title': 'Why Choose ParkirIn?',
    'search_feature_slot_title': 'Guaranteed Slot',
    'search_feature_slot_sub': 'Guaranteed space, secure 24/7 facilities.',
    'search_feature_biaya_title': 'Transparent Pricing',
    'search_feature_biaya_sub': 'No hidden fees at checkout.',
    'search_shuttle_title': 'Track Shuttle in Real-time',
    'search_shuttle_sub':
        'Monitor the shuttle bus location straight from your phone to the terminal.',
    'search_active_booking_parked': 'Vehicle Currently Parked',
    'search_active_booking_waiting': 'Active Booking Awaiting Check-in',
    'search_malam': 'nights',
    'bookings_appbar_title': 'My Bookings',
    'bookings_tab_aktif': 'Active',
    'bookings_tab_selesai': 'Completed',
    'bookings_tab_dibatalkan': 'Cancelled',
    'bookings_tab_kedaluwarsa': 'Expired',
    'bookings_empty': 'No bookings yet',
    'bookings_slot_label': 'Slot',
    'bookings_checkin_btn': 'Check-in',
    'bookings_checkout_btn': 'Check-out',
    'bookings_qr_btn': 'View QR Code',
    'bookings_expired_note':
        'Automatically cancelled due to missed check-in deadline',
    'profile_appbar_title': 'Profile',
    'profile_gold_member': 'Gold Member',
    'profile_my_details_title': 'My Details',
    'profile_my_details_sub': 'Personal info, ID, password',
    'profile_payment_title': 'Payment Methods',
    'profile_payment_sub': 'Cards, e-wallets, bank transfer',
    'profile_help_title': 'Help Center',
    'profile_help_sub': 'FAQs, contact support',
    'profile_favorites_title': 'My Favorites',
    'profile_favorites_sub': 'Parking locations you saved',
    'profile_notif_settings_title': 'Notification Settings',
    'profile_notif_settings_sub': 'Manage which notifications you receive',
    'profile_vehicles_title': 'My Vehicles',
    'profile_vehicles_sub': 'Manage saved license plates',
    'profile_invoice_title': 'Invoice History',
    'profile_invoice_sub': 'Download your transaction receipts',
    'profile_loyalty_title': 'Loyalty & Membership',
    'profile_referral_title': 'Invite Friends',
    'profile_referral_sub': 'Get Rp 25,000 per referral',
    'profile_terms_title': 'Terms & Conditions',
    'profile_terms_sub': 'Service policy & privacy',
    'profile_accessibility_title': 'Accessibility',
    'profile_accessibility_sub': 'Text size & high contrast',
    'profile_language_title': 'Language',
    'profile_language_sub': 'Indonesia / English',
    'profile_delete_account_title': 'Delete Account & Data',
    'profile_delete_account_sub': 'Manage or delete your personal data',
    'profile_logout': 'Logout',
    'profile_logout_confirm_title': 'Logout',
    'profile_logout_confirm_msg': 'Are you sure you want to log out?',
    'profile_cancel': 'Cancel',
    'notif_title': 'Notifications',
    'notif_subtitle': 'Stay updated on your upcoming trips and shuttle status.',
    'notif_mark_all_read': 'Mark all as read',
    'notif_pilih': 'Select',
    'notif_batal': 'Cancel',
    'notif_filter_semua': 'All',
    'notif_filter_reminder': 'Reminder',
    'notif_filter_shuttle': 'Shuttle',
    'notif_filter_booking': 'Booking',
    'notif_filter_flight': 'Flight',
    'notif_group_today': 'Today',
    'notif_group_yesterday': 'Yesterday',
    'notif_group_week': 'This Week',
    'notif_group_older': 'Older',
    'notif_empty_title': 'No notifications yet',
    'notif_empty_sub':
        'Updates on your bookings, shuttle, and flight\nwill appear here.',
    'notif_mark_read_btn': 'Mark as Read',
    'notif_delete_btn': 'Delete',
    'notif_appbar_title': 'Alerts',
    'notif_new_badge_suffix': 'new',
    'notif_booking_code_label': 'Booking code: ',
    'notif_phase2_badge': 'Phase 2',
    'loc_facilities_title': 'Security Facilities',
    'loc_accessible_note':
        'This location is elderly & wheelchair friendly (near lift/gate).',
    'loc_location_title': 'Location',
    'loc_per_night': ' / night',
    'loc_km_from_airport': 'km from airport',
    'loc_select_slot_btn': 'Select This Slot',
    'loc_reviews_title': 'User Reviews',
    'loc_reviews_suffix': 'reviews',
    'loc_no_reviews': 'No reviews yet for this location.',
    'slot_map_title': 'Select Parking Slot',
    'slot_legend_premium': 'Premium (near entrance)',
    'slot_legend_standard': 'Standard',
    'slot_legend_economy': 'Economy (far)',
    'slot_legend_occupied': 'Occupied',
    'slot_akses_jalan': 'Access Road',
    'slot_select_first': 'Select a Slot First',
    'slot_continue_with': 'Continue with Slot',
    'slot_baris_label': 'Row',
    'slot_dari_pintu_masuk': 'm from entrance',
    'slot_per_malam': '/night',
    'vehicle_appbar_title': 'Select Vehicle',
    'vehicle_slot_prefix': 'Slot',
    'vehicle_per_malam': '/night',
    'vehicle_pilih_title': 'Select Vehicle',
    'vehicle_tambah_btn': 'Add',
    'vehicle_utama_badge': 'DEFAULT',
    'vehicle_lanjut_btn': 'Continue to Summary',
    'vehicle_empty_title': 'No saved vehicles yet',
    'vehicle_empty_btn': 'Add Vehicle',
    'vehicle_lock_expired_title': 'Time Expired',
    'vehicle_lock_expired_msg':
        'The slot you selected has been released because the lock time expired. Please select a slot again.',
    'vehicle_back_home_btn': 'Back to Home',
    'summary_appbar_title': 'Summary & Payment',
    'summary_masuk': 'CHECK-IN',
    'summary_keluar': 'CHECK-OUT',
    'summary_malam': 'nights',
    'summary_slot_prefix': 'Slot',
    'summary_rincian_biaya': 'Cost Breakdown',
    'summary_tarif_dasar': 'Base rate',
    'summary_biaya_layanan': 'Service fee',
    'summary_total': 'Total',
    'summary_total_label': 'Total  ',
    'summary_metode_pembayaran': 'Payment Method',
    'summary_opsional_badge': 'Optional',
    'summary_bayar_sekarang': 'Pay Now',
    'summary_overstay_notice':
        'Additional fees (overstay fee) will be automatically charged if you exceed the booked duration. You will receive a notification before the deadline.',
    'summary_notif_title': 'Booking Successfully Confirmed',
    'summary_notif_desc_prefix': 'Slot',
    'summary_notif_desc_suffix': 'has been confirmed.',
    'summary_notif_action': 'View QR Code',
    'confirm_title': 'Booking Successful!',
    'confirm_subtitle':
        'Confirmation & QR Code have been sent for your booking.',
    'confirm_qr_note': 'Show this QR Code during check-in & check-out',
    'confirm_masuk': 'Check-in',
    'confirm_keluar': 'Check-out',
    'confirm_total_dibayar': 'Total Paid',
    'confirm_reminder_note':
        "We'll send a reminder 1 day before your check-in schedule.",
    'confirm_lihat_booking_btn': 'View My Booking',
    'confirm_kembali_beranda_btn': 'Back to Home',
    'checkin_appbar_title': 'Check-in',
    'checkin_waiting_title': 'Show this QR at the entrance gate',
    'checkin_success_title': 'Check-in Successful',
    'checkin_waiting_sub': 'Staff or kiosk will scan this QR Code',
    'checkin_success_sub':
        'Your vehicle is safely recorded in the parking area',
    'checkin_waiting_qr_status': 'Waiting for gate validation...',
    'checkin_success_banner': 'QR successfully validated by the entrance gate',
    'checkin_photo_toggle': 'Optional: Document Vehicle Condition',
    'checkin_photo_note':
        'To help with claims in case of damage during parking.',
    'checkin_photo_depan': 'Front',
    'checkin_photo_belakang': 'Rear',
    'checkin_photo_kiri': 'Left',
    'checkin_photo_kanan': 'Right',
    'checkin_lacak_shuttle_btn': 'Track Shuttle',
    'checkin_notif_title': 'Check-in Successful',
    'checkin_notif_desc_prefix': 'Vehicle',
    'checkin_notif_desc_middle': 'safely recorded at slot',
    'checkin_notif_action': 'View Booking',
    'checkout_overstay_warning':
        'You have exceeded the booking duration. An additional fee of {amount} will be automatically charged before the exit portal can be used.',
    'checkout_appbar_title': 'Check-out',
    'checkout_waiting_title': 'Show this QR at the exit gate',
    'checkout_waiting_sub': 'Staff or kiosk will scan this QR Code',
    'checkout_waiting_qr_status': 'Waiting for gate validation...',
    'checkout_photo_toggle': 'Optional: Final Vehicle Condition Verification',
    'checkout_photo_depan': 'Front',
    'checkout_photo_belakang': 'Rear',
    'checkout_photo_kiri': 'Left',
    'checkout_photo_kanan': 'Right',
    'checkout_invoice_title': 'Final Invoice',
    'checkout_success_title': 'Check-out Successful',
    'checkout_success_sub': 'Your parking lot is now available again',
    'checkout_kode_booking': 'Booking Code:',
    'checkout_tarif_dasar': 'Base rate',
    'checkout_malam': 'nights',
    'checkout_biaya_layanan': 'Service fee',
    'checkout_biaya_keterlambatan': 'Late fee',
    'checkout_total_akhir': 'Final Total',
    'checkout_selesai_btn': 'Done',
    'checkout_transport_btn': 'Find Onward Transport',
    'checkout_notif_success_title': 'Vehicle Successfully Picked Up',
    'checkout_notif_success_desc':
        'Vehicle {plate} has successfully checked out. Thank you!',
    'checkout_notif_success_action': 'View Invoice',
    'checkout_notif_overstay_title': 'Late Fee Charged',
    'checkout_notif_overstay_desc':
        'Booking {code} was charged an additional fee of {amount}.',
    'checkout_notif_overstay_action': 'View Detail',
    'shuttle_appbar_title': 'Track Shuttle',
    'shuttle_walking_title': 'Directions to Nearest Stop',
    'shuttle_slot_anda': 'Your Slot',
    'shuttle_halte_terdekat': 'Nearest Stop',
    'shuttle_meter_suffix': 'meters',
    'shuttle_menit_jalan_kaki': 'min walk',
    'shuttle_petunjuk_arah_btn': 'Open Directions',
    'shuttle_maps_error': 'Unable to open maps application',
    'shuttle_rute_title': 'Shuttle Route',
    'shuttle_titik_jemput': 'Pickup Point',
    'shuttle_titik_terminal': 'Terminal Point',
    'shuttle_berangkat_section': 'Shuttles En Route',
    'shuttle_standby_section': 'Shuttles Standby at Terminal',
    'shuttle_empty_berangkat': 'No shuttles currently en route.',
    'shuttle_empty_standby': 'No shuttles currently on standby.',
    'shuttle_baru_lewat': 'Just passed:',
    'shuttle_menuju': 'Heading to:',
    'shuttle_standby_di': 'Standby at',
    'shuttle_siap_berangkat': 'Ready to Depart',
    'shuttle_prefix': 'Shuttle',
    'shuttle_notif_title': 'Shuttle Available at Nearest Stop',
    'shuttle_notif_desc':
        'Shuttle is now standby at {halte}, ready to take you.',
    'shuttle_notif_action': 'Track Shuttle',
    'mydetails_appbar_title': 'My Details',
    'mydetails_section_personal': 'Personal Information',
    'mydetails_nama': 'Full Name',
    'mydetails_email': 'Email',
    'mydetails_telepon': 'Phone Number',
    'mydetails_section_identitas': 'Identity (ID/License)',
    'mydetails_nomor_identitas': 'ID Number',
    'mydetails_section_keamanan': 'Security',
    'mydetails_ubah_password': 'Change Password',
    'mydetails_simpan_btn': 'Save Changes',
    'mydetails_saved_snackbar': 'Data saved successfully',
    'mydetails_password_lama': 'Old Password',
    'mydetails_password_baru': 'New Password',
    'mydetails_simpan_password_btn': 'Save New Password',
    'payment_appbar_title': 'Payment Methods',
    'payment_utama_badge': 'DEFAULT',
    'payment_jadikan_utama': 'Set as Default',
    'payment_hapus': 'Delete',
    'payment_tambah_btn': 'Add Payment Method',
    'payment_kartu': 'Debit/Credit Card',
    'payment_ewallet': 'E-Wallet (GoPay/OVO/Dana)',
    'payment_va': 'Virtual Account',
    'addpayment_title_card': 'Add Debit/Credit Card',
    'addpayment_title_ewallet': 'Add E-Wallet',
    'addpayment_title_va': 'Add Virtual Account',
    'addpayment_nomor_kartu': 'Card Number',
    'addpayment_nama_pemegang': 'Cardholder Name',
    'addpayment_nama_hint': 'As shown on card',
    'addpayment_masa_berlaku': 'MM/YY',
    'addpayment_cvv': 'CVV',
    'addpayment_nomor_hp': 'Registered Phone Number',
    'addpayment_ewallet_note':
        "You'll be redirected to the e-wallet app for verification.",
    'addpayment_pilih_bank': 'Select Bank',
    'addpayment_va_note':
        'VA number will be generated automatically after confirmation.',
    'addpayment_security_note':
        'Your payment data is encrypted and stored securely.',
    'addpayment_simpan_btn': 'Save',
    'addpayment_wajib_diisi': 'Required',
    'addpayment_success_snackbar': 'Payment method added successfully',
    'fav_appbar_title': 'My Favorites',
    'fav_empty_title': 'No favorite locations yet',
    'fav_empty_sub': 'Tap the heart icon on search results to save a location.',
    'fav_per_malam': '/night',
    'vehicles_appbar_title': 'My Vehicles',
    'vehicles_utama_badge': 'DEFAULT',
    'vehicles_jadikan_utama': 'Set as Default',
    'vehicles_hapus': 'Delete',
    'vehicles_tambah_btn': 'Add Vehicle',
    'vehicles_dialog_title': 'Add Vehicle',
    'vehicles_plat_nomor': 'License Plate',
    'vehicles_merek_model': 'Brand & Model',
    'vehicles_tipe': 'Type (SUV/MPV)',
    'vehicles_warna': 'Color',
    'vehicles_simpan_btn': 'Save Vehicle',
    'help_appbar_title': 'Help Center',
    'help_search_hint': 'Search questions...',
    'help_faq_title': 'Frequently Asked Questions',
    'help_no_results': 'No matching questions found',
    'help_more_help': 'Still Need Help?',
    'help_livechat_title': '24-Hour Live Chat',
    'help_livechat_sub': 'Connect with our Customer Support team',
    'help_report_title': 'Report an Issue / Complaint',
    'help_faq_q1': 'How do I cancel a booking?',
    'help_faq_a1':
        'Go to Bookings > select an active booking > Reschedule/Cancel. Free cancellation if done at least 24 hours before check-in.',
    'help_faq_q2': 'What happens if I check out late?',
    'help_faq_a2':
        'The system automatically calculates an additional fee (overstay fee) based on the delay duration. You will receive a warning notification before the deadline.',
    'help_faq_q3': 'What if my vehicle gets damaged while parked?',
    'help_faq_a3':
        'We document vehicle condition photos at check-in and check-out as claim evidence. Contact Customer Support for further claims.',
    'help_faq_q4': 'Can I change my payment method?',
    'help_faq_a4':
        'Yes, manage your payment methods in Profile > Payment Methods.',
    'help_faq_q5': 'How do I track the shuttle?',
    'help_faq_a5':
        'Open your active booking detail, then tap "Track Shuttle" to see its position and real-time ETA.',
    'chat_appbar_online': 'Online 24 Hours',
    'chat_sos_btn': 'SOS',
    'chat_sos_dialog_title': 'Emergency Call (SOS)',
    'chat_sos_dialog_msg':
        "This will connect you directly to security staff/emergency hotline at the parking location. Continue?",
    'chat_sos_batal': 'Cancel',
    'chat_sos_confirm': 'Yes, Call Now',
    'chat_sos_connecting': 'Connecting to emergency staff...',
    'chat_input_hint': 'Type a message...',
    'chat_greeting': 'Hi there! How can we help with your parking booking?',
    'chat_autoresponse':
        'Thank you for your message. Our team will assist you shortly.',
    'report_appbar_title': 'Report Issue',
    'report_booking_terkait': 'Related booking:',
    'report_kategori_title': 'Issue Category',
    'report_deskripsi_title': 'Issue Description',
    'report_deskripsi_hint': 'Describe your issue in detail...',
    'report_lampiran_title': 'Attach Photo Evidence (optional)',
    'report_kirim_btn': 'Submit Report',
    'report_validation_snackbar': 'Please complete category and description',
    'report_success_title': 'Report Submitted',
    'report_success_msg':
        'Our team will review your report and contact you within 24 hours.',
    'report_selesai_btn': 'Done',
    'report_kategori_1': 'Damaged/Scratched Vehicle',
    'report_kategori_2': 'Incorrect Charge',
    'report_kategori_3': 'Shuttle Did Not Arrive',
    'report_kategori_4': 'Unfriendly Staff',
    'report_kategori_5': 'Payment Issue',
    'report_kategori_6': 'Other',
    'accessibility_appbar_title': 'Accessibility',
    'accessibility_ukuran_teks': 'Text Size',
    'accessibility_contoh_teks': 'Sample text at this size',
    'accessibility_kontras_tinggi': 'High Contrast',
    'accessibility_kontras_sub': 'Sharpen primary colors for easier reading',
    'language_appbar_title': 'Language',
    'language_note':
        'Translation currently covers main navigation and most app screens.',
    'delete_appbar_title': 'Delete Account & Data',
    'delete_unduh_data_title': 'Download My Data',
    'delete_unduh_data_sub': 'Get a copy of all your personal data',
    'delete_minta_btn': 'Request',
    'delete_warning':
        'Deleting your account will permanently remove all booking history, loyalty points, wallet balance, and vehicle data.',
    'delete_reason_title': 'Why do you want to delete your account?',
    'delete_feedback_hint': 'Additional feedback (optional)',
    'delete_confirm_checkbox':
        'I understand this action is permanent and cannot be undone',
    'delete_hapus_btn': 'Delete My Account',
    'delete_final_title': 'Final Confirmation',
    'delete_final_msg':
        'Your account and all personal data (booking history, vehicles, payment methods) will be permanently deleted within 30 days. This cannot be undone after the grace period ends.',
    'delete_batal': 'Cancel',
    'delete_ajukan_btn': 'Submit Deletion Request',
    'delete_submitted_title': 'Request Submitted',
    'delete_submitted_msg':
        'We have received your account deletion request. Confirmation will be sent to your registered email within 24 hours.',
    'delete_selesai_btn': 'Done',
    'delete_export_snackbar':
        'Data export request sent. You will receive an email with a copy of your data within 24 hours.',
    'delete_reason_1': 'No longer need the service',
    'delete_reason_2': 'Found an alternative',
    'delete_reason_3': 'Privacy/security concerns',
    'delete_reason_4': 'Difficult to use',
    'delete_reason_5': 'Other',
    'forgot_title': 'Forgot Password',
    'forgot_subtitle':
        "Enter your registered email or phone number. We'll send a verification code to reset your password.",
    'forgot_toggle_email': 'Email',
    'forgot_toggle_phone': 'Phone Number',
    'forgot_email_label': 'Email',
    'forgot_phone_label': 'Phone Number',
    'forgot_phone_hint': '08xxxxxxxxxx',
    'forgot_kirim_kode_btn': 'Send Verification Code',
    'forgot_kembali_login': 'Back to Sign In',
    'forgot_not_found_error': 'No account found with this contact',
    'resetotp_title': 'Verify Code',
    'resetotp_subtitle_prefix': 'A verification code has been sent to',
    'resetotp_verify_btn': 'Verify',
    'resetotp_resend_prefix': 'Resend code in',
    'resetotp_resend_btn': 'Resend Code',
    'resetotp_error': 'Enter the 6-digit OTP code',
    'newpass_title': 'Create New Password',
    'newpass_subtitle':
        'Your new password must be different from your previous password and at least 8 characters.',
    'newpass_field1': 'New Password',
    'newpass_field2': 'Confirm New Password',
    'newpass_simpan_btn': 'Save New Password',
    'newpass_error_short': 'Password must be at least 8 characters',
    'newpass_error_mismatch': "Password confirmation doesn't match",
    'newpass_success_title': 'Password Changed Successfully',
    'newpass_success_msg': 'Please sign in again using your new password.',
    'newpass_success_btn': 'Sign In Now',
  };
}
